name: CowPaths
main: com.ryanmichela.cowpaths.plugin.CowPaths
version: ${version}
website: https://github.com/tips48/CowPaths
author: Ryan Michela
description: >
             Simulate errosion, wear, and growth on your Minecraft maps.
