name: ${name}
main: ${groupId}.${artifactId}.plugin.${build.finalName}
version: ${version}
website: ${url}
authors: [4am, tips48, Tster, Ryan Michela]
description: >
             ${description}
